version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - MONGO_URI=mongodb://host.docker.internal:27017/client_management
    command: flask run --host=0.0.0.0 --port=5001



  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

 
  mongodb:
    image: mongo:6.0
    container_name: client-service-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=client-service-db
volumes:
  mongodb_data: 
  